create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(10, 2) not null default 0,
  symbol text not null default '✦',
  image_url text,
  description text not null default '',
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists image_url text;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  phone text not null,
  customer_name text not null,
  items jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null default 0,
  payment_method text not null,
  status text not null default 'بانتظار الدفع',
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "public can read categories" on public.categories;
drop policy if exists "public can add categories" on public.categories;
drop policy if exists "public can delete categories" on public.categories;
drop policy if exists "public can read products" on public.products;
drop policy if exists "public can add products" on public.products;
drop policy if exists "public can delete products" on public.products;
drop policy if exists "public can read orders" on public.orders;
drop policy if exists "public can add orders" on public.orders;
drop policy if exists "public can update orders" on public.orders;

create policy "public can read categories" on public.categories for select to anon using (true);
create policy "public can add categories" on public.categories for insert to anon with check (true);
create policy "public can delete categories" on public.categories for delete to anon using (true);
create policy "public can read products" on public.products for select to anon using (true);
create policy "public can add products" on public.products for insert to anon with check (true);
create policy "public can delete products" on public.products for delete to anon using (true);
create policy "public can read orders" on public.orders for select to anon using (true);
create policy "public can add orders" on public.orders for insert to anon with check (true);
create policy "public can update orders" on public.orders for update to anon using (true) with check (true);

insert into public.categories (name) values
  ('تصاميم اليرتات'),
  ('هويات البث'),
  ('قوالب جاهزة')
on conflict (name) do nothing;

delete from public.products
where id not in (select min(id) from public.products group by name);

insert into public.products (name, category, price, symbol, description)
select seed.name, seed.category, seed.price, seed.symbol, seed.description
from (values
  ('حزمة تنبيهات سماوية', 'تصاميم اليرتات', 39, '✦', 'مجموعة تنبيهات أنيقة لبثك بتفاصيل سماوية هادئة.'),
  ('هوية بث ليلية', 'هويات البث', 79, '◌', 'هوية متكاملة تمنح قناتك حضورًا واضحًا ومميزًا.'),
  ('شارات أعضاء الغزال', 'تصاميم اليرتات', 25, '♢', 'شارات عضوية متناسقة بتفاصيل ناعمة لعائلتك.'),
  ('قوالب منشورات', 'قوالب جاهزة', 29, '▦', 'قوالب مرنة وسريعة لتجهيز منشوراتك اليومية.')
) as seed(name, category, price, symbol, description)
where not exists (select 1 from public.products existing where existing.name = seed.name);